# Generated by Django 5.2.7 on 2025-11-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
