# Generated by Django 5.2.7 on 2025-11-15 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.estadopedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.metodopago'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(default='delivery', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(),
        ),
    ]
