# Generated by Django 5.2.7 on 2025-11-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_pedido_payment_id_alter_pedido_tipo_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(default='delivery', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(),
        ),
    ]
