# Generated by Django 5.2.7 on 2025-11-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_pedido_payment_id_alter_pedido_tipo_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ticket_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
