# Generated by Django 5.2.7 on 2025-11-17 00:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_pedido_ticket_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='peso_total',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('delivery', 'Delivery'), ('retiro', 'Retiro en tienda')], default='delivery', max_length=20),
        ),
    ]
