# Generated by Django 5.2.7 on 2025-11-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_pedido_costo_envio_pedido_peso_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='blue_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
    ]
