# Generated by Django 5.2.7 on 2025-11-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_estadopago_alter_estadopedido_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='costo_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='peso_total',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='peso_total_item',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='peso_unitario',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio_min',
            field=models.IntegerField(default=0),
        ),
    ]
