# Generated by Django 5.2.7 on 2025-11-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_remove_pedido_costo_envio_remove_pedido_peso_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
